TestTokenmanager/Models/Token.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace TestTokenmanager.Models
{
    public class Token
    {
        public int Id { get; set; }
        [Display(Name="私钥")]
        [Required(ErrorMessage = "必填字段")]
        public string SecretToken { get; set; }
        [Display(Name = "公钥")]
        [Required(ErrorMessage = "必填字段")]
        public string OpenToken { get; set; }
        [Display(Name="第三方名称")]
        [Required(ErrorMessage="必填字段")]
        public string ThirdPartName { get; set; }
        [Display(Name="联系方式")]
        [RegularExpression(@"^[1][3578]\d{9}$",ErrorMessage="无效手机号")]
        public string Telphone { get; set; }
    }
}

TestTokenmanager/Models/TokenStatus.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestTokenmanager.Models
{
    public class TokenStatus
    {
        public string Code { get; set; }
        public string Message { get; set; }
    }
}

TestTokenmanager/Controllers/TokenManageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestTokenmanager.Models;
using TestTokenmanager.TokenDAL;

namespace TestTokenmanager.Controllers
{
    public class TokenManageController : Controller
    {
        private TokenDbContext db;
        public TokenManageController()
        {
            db = new TokenDbContext();
        }
        public ActionResult Index()
        {
            var tokens = db.Set<Token>().ToList();
            return View(tokens);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Token entity)
        {
            if (ModelState.IsValid)
            {
                db.Set<Token>().Add(entity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public ActionResult Details(int id = 0)
        {
            var token = db.Set<Token>().Find(id);
            return View(token);
        }
        public ActionResult Edit(int id = 0)
        {
            var token = db.Set<Token>().Find(id);
            return View(token);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Token entity)
        {
            if (ModelState.IsValid)
            {
                db.Entry<Token>(entity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        public ActionResult Delete(int id = 0)
        {
            var token = db.Set<Token>().Find(id);
            db.Set<Token>().Remove(token);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public string CreateSecret()
        {
            long i = 1;
            foreach (byte b in Guid.NewGuid().ToByteArray())
            {
                i *= ((int)b + 1);
            }
            return string.Format("{0:x}", i - DateTime.Now.Ticks);
        }
        [HttpGet]
        public TokenStatus TokenError(int type)
        {
            TokenStatus ts = new TokenStatus();
            switch (type)
            {
                case 1:
                    {
                        ts.Code = "0000";
                        ts.Message = "缺少TimeStamp参数";
                        break;
                    }
                case 2:
                    {
                        ts.Code = "1000";
                        ts.Message = "时间戳不在合理范围内,请检测您服务器的当前时间";
                        break;
                    }
                case 4:
                    {
                        ts.Code = "2000";
                        ts.Message = "公钥不存在";
                        break;
                    }
                case 8:
                    {

                        ts.Code = "3000";
                        ts.Message = "缺失PublicKey参数";
                        break;
                    }
                case 16:
                    {
                        ts.Code = "5000";
                        ts.Message = "缺失PrivateKey参数";
                        break;
                    }
                default:
                    {
                        ts.Code = "4000";
                        ts.Message = "提供的参数有错误";
                        break;
                    }
            }
            return ts;
        }
    }
}

TestTokenmanager/Views/Shared/TokenLayout.cshtml
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/sticky-footer.css" rel="stylesheet" />
</head>

<body>

    <!-- Begin page content -->
    <div class="container">
        @RenderBody()
    </div>
    
    <footer class="footer">
        <div class="container">
            <p class="text-muted">&copy;@DateTime.Now.Year  Powered By 小熊有话说</p>
        </div>
    </footer>
    @RenderSection("scripts", required: false)
</body>
</html>

TestTokenmanager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

TestTokenmanager/Views/TokenManage/Create.cshtml
@model TestTokenmanager.Models.Token

@{
    ViewBag.Title = "新增第三方";
    Layout = "~/Views/Shared/TokenLayout.cshtml";
}

<h2>新建Token</h2>


@using (Html.BeginForm("Create", "TokenManage", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()
    <fieldset>
        <div id="legend" class="">
            <legend class="">新建</legend>
        </div>
        @Html.ValidationSummary(true)

        <div class="control-group">
            @Html.LabelFor(model => model.SecretToken, new { @class = "control-label col-md-2" })
            <div class="controls">
                <input type="text" class="form-control" placeholder="点我生成" name="SecretToken" id="SecretToken" />
                @Html.ValidationMessageFor(model => model.SecretToken)
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.OpenToken, new { @class = "control-label col-md-2" })
            <div class="controls">
                <input type="text" class="form-control" placeholder="点我生成" name="OpenToken" id="OpenToken" />
                @Html.ValidationMessageFor(model => model.OpenToken)
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.ThirdPartName, new { @class = "control-label col-md-2" })
            <div class="controls">
                <input id="ThirdPartName" class="form-control" type="text" value="" name="ThirdPartName" data-val-required="第三方名称 字段是必需的。" data-val="true">
                @Html.ValidationMessageFor(model => model.ThirdPartName)
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Telphone, new { @class = "control-label col-md-2" })
            <div class="controls">
                <input type="text" value="" name="Telphone" id="Telphone" data-val-regex-pattern="^[1][3578]\d{9}$" data-val-regex="字段 联系方式 必须与正则表达式“^[1][3578]\d{9}$”匹配。" data-val="true" class="form-control">
                @Html.ValidationMessageFor(model => model.Telphone)
            </div>
        </div>

        <div class="control-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="确定" class="btn btn-success" />
            </div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("返回列表页", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">
        $("#SecretToken").click(function () {
            $.ajax({
                url: '/TokenManage/CreateSecret',
                type: 'GET',
                datatype: 'text',
                success: function (res) {
                    console.log(res);
                    if (res) {
                        $("#SecretToken").val(res);
                    }
                }
            });
        });
        $("#OpenToken").click(function () {
            $.ajax({
                url: '/TokenManage/CreateSecret',
                type: 'GET',
                datatype: 'text',
                success: function (res) {
                    console.log(res);
                    if (res) {
                        $("#OpenToken").val(res);
                    }
                }
            });
        });
    </script>
}

TestTokenmanager/Views/TokenManage/Details.cshtml
@model TestTokenmanager.Models.Token

@{
    ViewBag.Title = this.Model.ThirdPartName + "Details";
    Layout = "~/Views/Shared/TokenLayout.cshtml";
}

<h2> @this.Model.ThirdPartName Details</h2>

<div>
    <h4>Token</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SecretToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecretToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OpenToken)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OpenToken)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThirdPartName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThirdPartName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telphone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telphone)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("返回列表页", "Index")
</p>

TestTokenmanager/Views/TokenManage/Edit.cshtml
@model TestTokenmanager.Models.Token

@{
    ViewBag.Title = "编辑" + this.Model.ThirdPartName;
    Layout = "~/Views/Shared/TokenLayout.cshtml";
}

<h2>Token 编辑页</h2>

@using (Html.BeginForm("Edit","TokenManage", FormMethod.Post))
{
    @Html.AntiForgeryToken()
   
    <fieldset>
        <div id="legend" class="">
            <legend class="">编辑</legend>
        </div>
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        <div class="control-group">
            @Html.LabelFor(model => model.SecretToken, new { @class = "control-label col-md-2" })
            <div class="controls">
                <input type="text" class="form-control" title="点我更新" data-val-required="*" name="SecretToken" id="SecretToken" value=@this.Model.SecretToken />
                @Html.ValidationMessageFor(model => model.SecretToken)
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.OpenToken, new { @class = "control-label col-md-2" })
            <div class="controls">
                <input type="text" class="form-control" title="点我更新" data-val-required="*" name="OpenToken" id="OpenToken" value=@this.Model.OpenToken />
                @Html.ValidationMessageFor(model => model.OpenToken)
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.ThirdPartName, new { @class = "control-label col-md-2" })
            <div class="controls">
                <input id="ThirdPartName" class="form-control" type="text" value=@this.Model.ThirdPartName name="ThirdPartName" data-val-required="*" data-val="true" >
                @Html.ValidationMessageFor(model => model.ThirdPartName)
            </div>
        </div>

        <div class="control-group">
            @Html.LabelFor(model => model.Telphone, new { @class = "control-label col-md-2" })
            <div class="controls">
                <input type="text" value=@this.Model.Telphone name="Telphone" id="Telphone" data-val-regex-pattern="^[1][3578]\d{9}$" data-val-regex="字段 联系方式 必须与正则表达式“^[1][3578]\d{9}$”匹配。" data-val="true" class="form-control">
                @Html.ValidationMessageFor(model => model.Telphone)
            </div>
        </div>

        <div class="control-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="确定" class="btn btn-success" />
            </div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("返回列表页", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript">
        $("#SecretToken").click(function () {
            $.ajax({
                url: '/TokenManage/CreateSecret',
                type: 'GET',
                datatype: 'text',
                success: function (res) {
                    console.log(res);
                    if (res) {
                        $("#SecretToken").val(res);
                    }
                }
            });
        });
        $("#OpenToken").click(function () {
            $.ajax({
                url: '/TokenManage/CreateSecret',
                type: 'GET',
                datatype: 'text',
                success: function (res) {
                    console.log(res);
                    if (res) {
                        $("#OpenToken").val(res);
                    }
                }
            });
        });
    </script>
}

TestTokenmanager/Views/TokenManage/Index.cshtml
@model IEnumerable<TestTokenmanager.Models.Token>

@{
    ViewBag.Title = "Token管理页";
    Layout = "~/Views/Shared/TokenLayout.cshtml";
}

<h2>Token管理页</h2>

<p>
    @Html.ActionLink("新增", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SecretToken)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpenToken)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ThirdPartName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telphone)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.SecretToken)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OpenToken)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ThirdPartName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telphone)
        </td>
        <td>
            @Html.ActionLink("编辑", "Edit", new { id=item.Id }) |
            @Html.ActionLink("详细", "Details", new { id=item.Id }) |
            @Html.ActionLink("删除", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>